import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { PushProvider } from '../src/push/push.types';
import { FakePushAdapter } from '../src/push/fake-push.adapter';

describe('Message notifications (e2e)', () => {
  let app: INestApplication; let prisma: PrismaService; let fake: FakePushAdapter; let aId: string; let bId: string; let aToken: string; let bToken: string; let groupId: string; let venueId: string;
  const auth=(token:string)=>({ Authorization: 'Bearer '+token });
  const register=async(name:string)=>{ const r=await request(app.getHttpServer()).post('/auth/register').send({name,email:`msg-${Date.now()}-${Math.random()}@teste.com`,password:'Teste@123456'}); if(r.status!==201) throw new Error('register '+JSON.stringify(r.body)); return { id:r.body.user.id, token:r.body.accessToken }; };
  const ensureAccepted=async(requesterId:string,addresseeId:string)=>prisma.friendship.upsert({where:{requesterId_addresseeId:{requesterId,addresseeId}},update:{status:'ACCEPTED'},create:{requesterId,addresseeId,status:'ACCEPTED'}});
  beforeAll(async()=>{ const mod=await Test.createTestingModule({imports:[AppModule]}).overrideProvider(PushProvider).useValue(new FakePushAdapter()).compile(); app=mod.createNestApplication(); app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true})); await app.init(); prisma=app.get(PrismaService); fake=mod.get(PushProvider) as FakePushAdapter; const a=await register('User A'); const b=await register('User B'); aId=a.id;aToken=a.token;bId=b.id;bToken=b.token; await request(app.getHttpServer()).post('/notifications/devices').set(auth(bToken)).send({token:'ExpoPushToken[ExponentPushTokenTest1234567890]',platform:'IOS'}).expect(201); await request(app.getHttpServer()).post('/notifications/devices').set(auth(aToken)).send({token:'ExpoPushToken[owner-a-test-1234567890]',platform:'IOS'}).expect(201); const venue=await prisma.venue.create({data:{name:'Message Venue',category:'Bar',address:'Rua Teste',latitude:0,longitude:0}}); venueId=venue.id; const group=await prisma.group.create({data:{name:'Message Group',venueId,creatorId:aId,members:{create:{userId:aId}}}}); groupId=group.id; });
  beforeEach(async()=>{ if (aId && bId) await ensureAccepted(aId,bId); });
  afterAll(async()=>{ await prisma.user.deleteMany({where:{id:{in:[aId,bId]}}}); await prisma.venue.deleteMany({where:{id:venueId}}); await app.close(); });
  it('dispatches FRIEND_REQUEST and FRIEND_ACCEPTED through fake DI',async()=>{ fake.reset(); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:true,friendRequests:true}).expect(200); const c=await register('User C'); await request(app.getHttpServer()).post('/notifications/devices').set(auth(c.token)).send({token:'ExpoPushToken[friend-c-test-1234567890]',platform:'IOS'}).expect(201); const req=await request(app.getHttpServer()).post('/friends/request').set(auth(c.token)).send({addresseeId:bId}).expect(201); const n=await prisma.notification.findFirst({where:{userId:bId,type:'FRIEND_REQUEST'},orderBy:{createdAt:'desc'}}); expect(n).not.toBeNull(); expect(fake.messages).toHaveLength(1); fake.reset(); await request(app.getHttpServer()).patch('/friends/requests/'+req.body.id+'/accept').set(auth(bToken)).expect(200); expect(fake.messages.some(m=>m.data?.type==='FRIEND_ACCEPTED')).toBe(true); await prisma.user.delete({where:{id:c.id}}); });
  it('persists DM notification with generic private-safe content',async()=>{ fake.reset(); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:true,messages:true}).expect(200); const sentinel='PRIVATE_MESSAGE_SENTINEL_123'; await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(aToken)).send({text:sentinel}).expect(201); const n=await prisma.notification.findFirst({where:{userId:bId,type:'DIRECT_MESSAGE'},orderBy:{createdAt:'desc'}}); expect(n).not.toBeNull(); expect(n!.message).not.toContain(sentinel); expect(fake.messages).toHaveLength(1); expect(fake.messages[0].body).not.toContain(sentinel); });
  it('persists group notifications only for other members',async()=>{ fake.reset(); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:true,messages:true}).expect(200); await prisma.groupMember.create({data:{groupId,userId:bId}}).catch(()=>undefined); const sentinel='GROUP_PRIVATE_SENTINEL_456'; await request(app.getHttpServer()).post('/groups/'+groupId+'/messages').set(auth(aToken)).send({text:sentinel}).expect(201); const ns=await prisma.notification.findMany({where:{type:'GROUP_MESSAGE',referenceId:groupId}}); expect(ns.some(n=>n.userId===bId)).toBe(true); expect(ns.some(n=>n.userId===aId)).toBe(false); expect(fake.messages).toHaveLength(1); expect(fake.messages[0].body).not.toContain(sentinel); });
  it('honors category and global push preferences while persisting notifications',async()=>{ fake.reset(); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:true,messages:false}).expect(200); const c=await register('User D'); await ensureAccepted(c.id,bId); await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(c.token)).send({text:'category-off'}).expect(201); expect(await prisma.notification.count({where:{userId:bId,type:'DIRECT_MESSAGE'}})).toBeGreaterThan(0); expect(fake.messages).toHaveLength(0); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:false,messages:true}).expect(200); const d=await register('User E'); await ensureAccepted(d.id,bId); await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(d.token)).send({text:'global-off'}).expect(201); expect(fake.messages).toHaveLength(0); await prisma.user.deleteMany({where:{id:{in:[c.id,d.id]}}}); });
  it('absorbs transient provider failure without failing message creation',async()=>{ fake.reset(); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:true,messages:true}).expect(200); fake.setNextStatus('TRANSIENT_ERROR'); await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(aToken)).send({text:'failure'}).expect(201); expect(await prisma.notification.count({where:{userId:bId,type:'DIRECT_MESSAGE'}})).toBeGreaterThan(0); });
  it('dispatches group invite and accepted notifications',async()=>{ fake.reset(); const f=await register('User F'); await request(app.getHttpServer()).post('/notifications/devices').set(auth(f.token)).send({token:'ExpoPushToken[group-f-test-1234567890]',platform:'IOS'}).expect(201); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(f.token)).send({pushEnabled:true,groupInvites:true}).expect(200); const invite=await request(app.getHttpServer()).post('/groups/'+groupId+'/invites').set(auth(aToken)).send({receiverId:f.id}).expect(201); expect(fake.messages.some(m=>m.data?.type==='GROUP_INVITE')).toBe(true); fake.reset(); await request(app.getHttpServer()).patch('/invites/'+invite.body.id+'/accept').set(auth(f.token)).expect(200); expect(fake.messages.some(m=>m.data?.type==='GROUP_INVITE_ACCEPTED')).toBe(true); await prisma.user.delete({where:{id:f.id}}); });
});
