import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';
import { PushProvider } from '../src/push/push.types';
import { FakePushAdapter } from '../src/push/fake-push.adapter';
import { PushReceiptService } from '../src/notifications/push-receipt.service';

describe('Push receipts (e2e)', () => {
  let app: INestApplication; let prisma: PrismaService; let fake: FakePushAdapter; let processor: PushReceiptService; let aId:string; let bId:string; let aToken:string; let bToken:string;
  const auth=(t:string)=>({Authorization:'Bearer '+t});
  beforeAll(async()=>{ const mod=await Test.createTestingModule({imports:[AppModule]}).overrideProvider(PushProvider).useValue(new FakePushAdapter()).compile(); app=mod.createNestApplication(); app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true})); await app.init(); prisma=app.get(PrismaService); fake=mod.get(PushProvider) as FakePushAdapter; processor=app.get(PushReceiptService); const stamp=Date.now(); const a=await request(app.getHttpServer()).post('/auth/register').send({name:'Receipt Sender',email:`receipt-s-${stamp}@teste.com`,password:'Teste@123456'}).expect(201); const b=await request(app.getHttpServer()).post('/auth/register').send({name:'Receipt Receiver',email:`receipt-r-${stamp}@teste.com`,password:'Teste@123456'}).expect(201); aId=a.body.user.id;aToken=a.body.accessToken;bId=b.body.user.id;bToken=b.body.accessToken; await request(app.getHttpServer()).post('/notifications/devices').set(auth(bToken)).send({token:`ExpoPushToken[receipt-${stamp}]`,platform:'IOS'}).expect(201); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:true,messages:true}).expect(200); });
  afterAll(async()=>{ await prisma.user.deleteMany({where:{id:{in:[aId,bId]}}}); await app.close(); });
  it('persists accepted ticket and processes delivered receipt',async()=>{ fake.reset(); await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(aToken)).send({text:'receipt-test'}).expect(201); const delivery=await prisma.pushDelivery.findFirst({where:{notification:{userId:bId,type:'DIRECT_MESSAGE'}},orderBy:{createdAt:'desc'}}); expect(delivery).not.toBeNull(); fake.setReceipt(delivery!.ticketId,{status:'DELIVERED'}); await processor.processPending(0); expect((await prisma.pushDelivery.findUnique({where:{id:delivery!.id}}))!.status).toBe('DELIVERED'); });
  it('disables device after DeviceNotRegistered receipt',async()=>{ fake.reset(); await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(aToken)).send({text:'invalid-receipt'}).expect(201); const delivery=await prisma.pushDelivery.findFirst({where:{notification:{userId:bId,type:'DIRECT_MESSAGE'},status:'PENDING'},orderBy:{createdAt:'desc'}}); expect(delivery).not.toBeNull(); fake.setReceipt(delivery!.ticketId,{status:'INVALID_TOKEN',errorCode:'DeviceNotRegistered'}); await processor.processPending(0); expect((await prisma.pushDelivery.findUnique({where:{id:delivery!.id}}))!.status).toBe('FAILED'); expect((await prisma.pushDevice.findFirst({where:{userId:bId}}))!.disabledAt).not.toBeNull(); });
  it('keeps notification source of truth when push is disabled',async()=>{ fake.reset(); await request(app.getHttpServer()).patch('/notifications/preferences').set(auth(bToken)).send({pushEnabled:false,messages:true}).expect(200); const before=await prisma.notification.count({where:{userId:bId,type:'DIRECT_MESSAGE'}}); await request(app.getHttpServer()).post('/direct-messages/'+bId).set(auth(aToken)).send({text:'push-off'}).expect(201); expect(await prisma.notification.count({where:{userId:bId,type:'DIRECT_MESSAGE'}})).toBe(before+1); expect(fake.messages).toHaveLength(0); expect(await prisma.pushDelivery.count({where:{notification:{userId:bId,type:'DIRECT_MESSAGE'}}})).toBeGreaterThanOrEqual(1); });
});