import { NotificationPushService } from './notification-push.service';

describe('NotificationPushService', () => {
  const prefs = { findMany: jest.fn() }; const devices = { findMany: jest.fn(), updateMany: jest.fn() }; const delivery = { createMany: jest.fn() }; const push = { sendBatch: jest.fn() }; let service: NotificationPushService;
  beforeEach(() => { jest.clearAllMocks(); service = new NotificationPushService({ notificationPreferences: prefs, pushDevice: devices, pushDelivery: delivery } as never, push as never); prefs.findMany.mockResolvedValue([{ userId: 'u1', pushEnabled: true, friendRequests: true, groupInvites: true, messages: true }]); devices.findMany.mockResolvedValue([{ id: 'd1', userId: 'u1', token: 'ExpoPushToken[a]' }, { id: 'd2', userId: 'u1', token: 'ExpoPushToken[b]' }]); push.sendBatch.mockResolvedValue([]); });
  const n = (type = 'FRIEND_REQUEST', userId = 'u1') => ({ id: 'n1', userId, type, title: 'Title', message: 'Body', referenceId: 'r1', referenceType: 'friendship' });
  it('maps friend notifications and sends one batch to active devices', async () => { await service.dispatch(n()); expect(push.sendBatch).toHaveBeenCalledTimes(1); expect(push.sendBatch.mock.calls[0][0]).toHaveLength(2); expect(push.sendBatch.mock.calls[0][0][0].data).toEqual(expect.objectContaining({ notificationId: 'n1', type: 'FRIEND_REQUEST' })); });
  it('maps message notifications and dispatches many users in one call', async () => { prefs.findMany.mockResolvedValue([{ userId:'u1',pushEnabled:true,friendRequests:true,groupInvites:true,messages:true },{ userId:'u2',pushEnabled:true,friendRequests:true,groupInvites:true,messages:true }]); devices.findMany.mockResolvedValue([{id:'d1',userId:'u1',token:'ExpoPushToken[a]'},{id:'d2',userId:'u2',token:'ExpoPushToken[b]'}]); await service.dispatchMany([n('GROUP_MESSAGE','u1'),n('DIRECT_MESSAGE','u2')]); expect(prefs.findMany).toHaveBeenCalledTimes(1); expect(devices.findMany).toHaveBeenCalledTimes(1); expect(push.sendBatch).toHaveBeenCalledTimes(1); expect(push.sendBatch.mock.calls[0][0]).toHaveLength(2); });
  it('skips globally disabled and category-disabled preferences', async () => { prefs.findMany.mockResolvedValue([{ userId:'u1',pushEnabled:false,friendRequests:true,groupInvites:true,messages:true }]); await service.dispatch(n()); expect(push.sendBatch).not.toHaveBeenCalled(); prefs.findMany.mockResolvedValue([{ userId:'u1',pushEnabled:true,friendRequests:false,groupInvites:true,messages:true }]); await service.dispatch(n()); expect(push.sendBatch).not.toHaveBeenCalled(); });
  it('skips unknown types and users without active devices', async () => { await service.dispatch(n('UNKNOWN')); expect(prefs.findMany).not.toHaveBeenCalled(); devices.findMany.mockResolvedValue([]); await service.dispatch(n()); expect(push.sendBatch).not.toHaveBeenCalled(); });
  it('uses messages preference for message notifications', async () => { prefs.findMany.mockResolvedValue([{ userId:'u1',pushEnabled:true,friendRequests:true,groupInvites:true,messages:false }]); await service.dispatch(n('GROUP_MESSAGE')); expect(push.sendBatch).not.toHaveBeenCalled(); });
  it('persists accepted tickets and disables immediate invalid devices', async () => { push.sendBatch.mockResolvedValue([{ deviceId:'d1', status:'ACCEPTED', ticketId:'t1' }, { deviceId:'d2', status:'INVALID_TOKEN' }]); await service.dispatch(n()); expect(delivery.createMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.arrayContaining([expect.objectContaining({ pushDeviceId:'d1', ticketId:'t1', status:'PENDING' })]), skipDuplicates:true })); expect(devices.updateMany).toHaveBeenCalled(); });
  it('swallows provider failures best-effort', async () => { push.sendBatch.mockRejectedValue(new Error('provider')); await expect(service.dispatch(n('GROUP_INVITE'))).resolves.toBeUndefined(); });
});